### PR TITLE
remove lsstswBuild.sh's automatic addition of master to ref list

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by timj** [comment]
My real question is what does this get replaced with? What is ensuring that the branch is reasonable? I'm sure there's a plan but I'd prefer a bit more reasoning in the commit message. Is it ever possible for `$BRANCH` to be unset?

**Comment by jhoblitt** [comment]
@timj The script currently does work without `--branch` and `lsst_build` will append `master` in the ref list if it isn't specified as an argument.  However, now that you mention it, I'm not sure why `--branch` isn't treated as a mandatory parameter since the getopt specification for `branch` has a colon appended -- which is supposed to make it mandatory.  I will investigate this before merging.

**Comment by jhoblitt** [comment]
OK - the answer is my memory is terrible.  The colon means that the option flag requires an argument, not that the flag itself is mandatory.

**Comment by jhoblitt** [comment]
The commit message has been amended with a description of why this change was necessary.

**Pull request merged**
